---
- name: Generate and disribute keys
  vars:
    user: ubuntu
  hosts: localhost
  tasks:
    - name: Distribute key
      shell:
        cmd: cat /root/.ssh/id_rsa.pub | ssh -i /root/devops -o "StrictHostKeyChecking = no" {{ user }}@{{ item }} "cat >> ~/.ssh/authorized_keys"
      with_items:
       - 172.31.39.247
       - 172.31.39.166
